name: ZthTerminal3EndAutoRenew
version: "1.0"
main: ink.magma.zthTerminal3EndAutoRenew.ZthTerminal3EndAutoRenew
api-version: "1.20"
authors: [Magma]
commands:
  zth-end-renew:
    description: "Manages the ZthTerminal3EndAutoRenew plugin, including reloads and reset schedule."
    aliases: [zthautorenew, zthrenew, ztrend]
    permission: zth.endrenew.use # A general use permission, specific sub-commands have their own.
    usage: |
      /<command> reload
      /<command> list
      /<command> add <yyyy-MM-dd HH:mm:ss>
      /<command> remove <yyyy-MM-dd HH:mm:ss>
permissions:
  zth.endrenew.use:
    description: "Allows basic usage of the zthautorenew command."
    default: op
  zth.endrenew.reload:
    description: "Allows reloading the plugin configuration."
    default: op
  zth.endrenew.manage:
    description: "Allows managing the End reset schedule (list, add, remove times)."
    default: op
