# 末地定时刷新插件配置

timezone: Asia/Shanghai

refresh-times:
  - '2025-06-07 20:00:00'
  - '2025-07-05 20:00:00'
  - '2025-08-02 20:00:00'

bossbar-message: "<gradient:#ce9ffc:#7367f0>距离末地重置还有 {time}</gradient>"

dragon-egg-lore:
  - "<i:false><white>{player}达成了目标<green>[下一世代]</green></white></i>"
  - "<i:false><dark_gray><{date}></dark_gray></i>"

announce-winner: "恭喜 <aqua>{player}</aqua> 拾取了龙蛋!"
announce-egg-reset: "<red>悲报:</red> 龙蛋落入虚空，将在 1 分钟后重置到传送门上方!"
egg-reset-bossbar-title: "<gradient:#ce9ffc:#7367f0>龙蛋将在 <white>{time}</white> 秒后再次刷新</gradient>"
end-reset-broadcast-message: "<#FF00FF>[末地刷新] <#FFC0CB>末地已重置，新的冒险开始了!"